CREATE TABLE "myCrypto" IF NOT EXISTS (
	"id"	INTEGER NOT NULL UNIQUE,
	"date"	TEXT NOT NULL,
	"time"	TEXT NOT NULL,
	"desde"	TEXT NOT NULL,
	"Q_desde"	REAL NOT NULL,
	"hasta"	TEXT NOT NULL,
	"Q_hasta"	REAL NOT NULL,
	"PU"	REAL NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
)